<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <artifactId>evolutus-solutions</artifactId>

  <name>Evolutus solutions</name>
  <description>Evolutus solutions module</description>

  <properties>
    <jooq.version>3.5.3</jooq.version>
    <h2.version>1.4.186</h2.version>
    <velocity.version>1.7</velocity.version>
    <junit.version>4.11</junit.version>
    <guava.version>18.0</guava.version>
    <apache.commons.version>3.3.2</apache.commons.version>
    <apache.commons.io.version>2.4</apache.commons.io.version>
    <c3p0.version>0.9.5</c3p0.version>
  </properties>

  <parent>
    <groupId>pl.edu.agh</groupId>
    <artifactId>evolutus</artifactId>
    <version>1.0-SNAPSHOT</version>
  </parent>

  <dependencies>

    <dependency>
      <groupId>org.apache.velocity</groupId>
      <artifactId>velocity</artifactId>
      <version>${velocity.version}</version>
    </dependency>

    <dependency>
      <groupId>org.jage.services</groupId>
      <artifactId>core</artifactId>
      <version>${jage.version}</version>
    </dependency>

    <dependency>
      <groupId>org.jage.platform</groupId>
      <artifactId>cli-bootstrapper</artifactId>
      <version>${jage.version}</version>
    </dependency>

    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>${junit.version}</version>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
      <version>${guava.version}</version>
    </dependency>

    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
      <version>${apache.commons.version}</version>
    </dependency>

    <dependency>
      <groupId>commons-io</groupId>
      <artifactId>commons-io</artifactId>
      <version>${apache.commons.io.version}</version>
    </dependency>

    <dependency>
      <groupId>com.mchange</groupId>
      <artifactId>c3p0</artifactId>
      <version>${c3p0.version}</version>
    </dependency>

    <dependency>
      <groupId>org.mongodb</groupId>
      <artifactId>mongo-java-driver</artifactId>
      <version>3.0.0</version>
    </dependency>

    <dependency>
      <groupId>org.mongodb.morphia</groupId>
      <artifactId>morphia</artifactId>
      <version>0.111</version>
    </dependency>

    <dependency>
      <groupId>de.flapdoodle.embed</groupId>
      <artifactId>de.flapdoodle.embed.mongo</artifactId>
      <version>1.47.1</version>
    </dependency>

  </dependencies>

</project>
